import React from "react";

const ValidationMessage = {
  name: "Please enter user name",
  email: "Please enter official e-mail Id",
  validEmail: "Please enter valid official e-mail Id",
  password: "Please enter password",
  validPassword: "Please enter valid password",
  emailOTP: "Please enter OTP",
  brandName: "Please enter brand name",
  city: "Please enter city",
  compnayName: "Please enter company name",
  state: "Please enter state",
  businessLocation: "Please enter buniess location",
  whatsappNumber: "Please enter whatsapp number",
  isWhatsappVerified: "Please verify whatsapp number",
  gstNumber: "Please enter gst number",
  isGSTVerified: "Please verify gst number",
  whatsAppOTPNumber: "Please enter OTP",
  bank_name: "Please enter bank name",
  account_number: "Please enter account number",
  isBankAcVerified: "Please verify account number",
  ifsc_code: "Please enter IFSC code",
  upi_id: "Please enter upi id",
  isUPIVerified: "Please verify upi id",
  upload_cheque: "Please upload cheque",
  insta_link: "Please enter instagram link",
  facebook_link: "Please enter facebook link",
  twitter_link: "Please enter twitter link",
  insta_valid_link: "Please enter valid instagram link",
  facebook_valid_link: "Please enter valid facebook link",
  twitter_valid_link: "Please enter valid twitter link",
  valid_answer: "Answer is required",
  gst_doc_upload: "Please upload your gst certificate",
  aadhar_doc_upload: "Please upload your aadhar document",
  preference_selection: "Please select at least 2 categories",
  terms_and_condition: "Please accept terms and condition",
  e_signature_file: "Please upload your signature",
  bank_details: "Bank name, account number and ifsc code are required to verify bankd details",
  sendOTP: "Please send OTP",
  rupifi_option: "Please choose your option",
  rupifi_required: "You need to apply for Rupifi (BNPL) and complete your registration",
  rupifi_incomplete: "Your Rupifi (BNPL) registration is incomplete",
  rupifi_rejected: "Your Rupifi (BNPL) has been rejected",
  loginRequired: "Login is required before going ahead!!",
  signupSuccess: "Signup successfully. Welcome to NavTatva partnership program. Please login now to complete your profile.",
};

export default ValidationMessage;
